// Dados simulados para agendamentos
export const agendamentosMock = [
  {
    id: "agd-001",
    espacoId: "esp-001",
    titulo: "Treino Basquete Juvenil",
    responsavel: "Ana Paula Silva",
    contato: "ana.silva@email.com",
    data: "2025-06-10",
    horaInicio: 14,
    horaFim: 16,
    status: "confirmado",
    projetoId: "proj-002",
    tipo: "interno",
    descricao: "Treino regular da equipe juvenil de basquete.",
    recorrente: true,
    padraoRecorrencia: "semanal",
    diasRecorrencia: "Segunda, Quarta, Sexta",
    dataFimRecorrencia: "2025-08-10",
    observacoes: "Necessário preparar as cestas móveis.",
  },
  {
    id: "agd-002",
    espacoId: "esp-001",
    titulo: "Treino Futsal Feminino",
    responsavel: "Pedro Oliveira",
    contato: "pedro.oliveira@email.com",
    data: "2025-06-10",
    horaInicio: 16,
    horaFim: 18,
    status: "confirmado",
    projetoId: "proj-007",
    tipo: "interno",
    descricao: "Treino tático da equipe feminina de futsal.",
    recorrente: true,
    padraoRecorrencia: "semanal",
    diasRecorrencia: "Terça, Quinta",
    dataFimRecorrencia: "2025-07-30",
  },
  {
    id: "agd-003",
    espacoId: "esp-003",
    titulo: "Treino Ginástica Artística",
    responsavel: "Fernanda Costa",
    contato: "fernanda.costa@email.com",
    data: "2025-06-10",
    horaInicio: 9,
    horaFim: 12,
    status: "confirmado",
    projetoId: "proj-003",
    tipo: "interno",
    descricao: "Treino de rotinas para competição estadual.",
    recorrente: true,
    padraoRecorrencia: "semanal",
    diasRecorrencia: "Segunda, Quarta, Sexta",
    dataFimRecorrencia: "2025-07-15",
  },
  {
    id: "agd-004",
    espacoId: "esp-004",
    titulo: "Treino Velocistas",
    responsavel: "Roberto Almeida",
    contato: "roberto.almeida@email.com",
    data: "2025-06-10",
    horaInicio: 8,
    horaFim: 10,
    status: "confirmado",
    projetoId: "proj-004",
    tipo: "interno",
    descricao: "Treino de velocidade e resistência.",
    recorrente: false,
  },
  {
    id: "agd-005",
    espacoId: "esp-006",
    titulo: "Treino Tênis",
    responsavel: "Marcelo Santos",
    contato: "marcelo.santos@email.com",
    data: "2025-06-10",
    horaInicio: 10,
    horaFim: 12,
    status: "confirmado",
    projetoId: "proj-005",
    tipo: "interno",
    descricao: "Treino técnico individual.",
    recorrente: true,
    padraoRecorrencia: "semanal",
    diasRecorrencia: "Terça, Quinta, Sábado",
    dataFimRecorrencia: "2025-08-01",
  },
  {
    id: "agd-006",
    espacoId: "esp-005",
    titulo: "Preparação Física",
    responsavel: "Juliana Martins",
    contato: "juliana.martins@email.com",
    data: "2025-06-10",
    horaInicio: 16,
    horaFim: 18,
    status: "confirmado",
    projetoId: "proj-006",
    tipo: "interno",
    descricao: "Preparação física geral para atletas de diversas modalidades.",
    recorrente: true,
    padraoRecorrencia: "semanal",
    diasRecorrencia: "Segunda, Quarta, Sexta",
    dataFimRecorrencia: "2025-07-30",
  },
  {
    id: "agd-007",
    espacoId: "esp-001",
    titulo: "Competição Interescolar",
    responsavel: "Secretaria de Esportes",
    contato: "secretaria.esportes@email.com",
    data: "2025-06-11",
    horaInicio: 8,
    horaFim: 18,
    status: "confirmado",
    projetoId: null,
    tipo: "externo",
    descricao: "Competição entre escolas da região.",
    recorrente: false,
    observacoes: "Necessário preparar arquibancadas e sistema de som.",
  },
  {
    id: "agd-008",
    espacoId: "esp-004",
    titulo: "Avaliação Física Atletismo",
    responsavel: "Roberto Almeida",
    contato: "roberto.almeida@email.com",
    data: "2025-06-11",
    horaInicio: 14,
    horaFim: 16,
    status: "pendente",
    projetoId: "proj-004",
    tipo: "interno",
    descricao: "Avaliação física semestral dos atletas de atletismo.",
    recorrente: false,
  },
  {
    id: "agd-009",
    espacoId: "esp-003",
    titulo: "Treino Especial Ginástica",
    responsavel: "Fernanda Costa",
    contato: "fernanda.costa@email.com",
    data: "2025-06-11",
    horaInicio: 9,
    horaFim: 12,
    status: "confirmado",
    projetoId: "proj-003",
    tipo: "interno",
    descricao: "Treino especial com foco em competição nacional.",
    recorrente: false,
  },
  {
    id: "agd-010",
    espacoId: "esp-006",
    titulo: "Aula Particular Tênis",
    responsavel: "Marcelo Santos",
    contato: "marcelo.santos@email.com",
    data: "2025-06-11",
    horaInicio: 16,
    horaFim: 18,
    status: "rejeitado",
    projetoId: "proj-005",
    tipo: "interno",
    descricao: "Aula particular para atleta de alto rendimento.",
    recorrente: false,
    motivoRejeicao: "Conflito com manutenção programada da quadra.",
  },
  {
    id: "agd-011",
    espacoId: "esp-002",
    titulo: "Campeonato Regional de Natação",
    responsavel: "Confederação Regional de Natação",
    contato: "confederacao@email.com",
    data: "2025-06-15",
    horaInicio: 8,
    horaFim: 20,
    status: "pendente",
    projetoId: null,
    tipo: "externo",
    descricao: "Campeonato regional com participação de 15 clubes.",
    recorrente: false,
    observacoes: "Necessário preparar arquibancadas, cronometragem eletrônica e sistema de som.",
  },
  {
    id: "agd-012",
    espacoId: "esp-007",
    titulo: "Workshop de Nutrição Esportiva",
    responsavel: "Departamento de Nutrição",
    contato: "nutricao@email.com",
    data: "2025-06-12",
    horaInicio: 14,
    horaFim: 17,
    status: "confirmado",
    projetoId: null,
    tipo: "interno",
    descricao: "Workshop sobre nutrição para atletas de alto rendimento.",
    recorrente: false,
  },
  {
    id: "agd-013",
    espacoId: "esp-008",
    titulo: "Reunião Técnica",
    responsavel: "Coordenação Geral",
    contato: "coordenacao@email.com",
    data: "2025-06-13",
    horaInicio: 9,
    horaFim: 11,
    status: "confirmado",
    projetoId: null,
    tipo: "interno",
    descricao: "Reunião com todos os técnicos para alinhamento de metodologias.",
    recorrente: true,
    padraoRecorrencia: "mensal",
    dataFimRecorrencia: "2025-12-13",
  },
  {
    id: "agd-014",
    espacoId: "esp-001",
    titulo: "Torneio Beneficente",
    responsavel: "ONG Esporte para Todos",
    contato: "ong@email.com",
    data: "2025-06-20",
    horaInicio: 9,
    horaFim: 18,
    status: "pendente",
    projetoId: null,
    tipo: "externo",
    descricao: "Torneio beneficente com arrecadação de alimentos.",
    recorrente: false,
  },
  {
    id: "agd-015",
    espacoId: "esp-005",
    titulo: "Avaliação Médica",
    responsavel: "Departamento Médico",
    contato: "medico@email.com",
    data: "2025-06-14",
    horaInicio: 8,
    horaFim: 12,
    status: "confirmado",
    projetoId: null,
    tipo: "interno",
    descricao: "Avaliação médica semestral obrigatória para todos os atletas.",
    recorrente: false,
  },
  {
    id: "agd-016",
    espacoId: "esp-004",
    titulo: "Manutenção da Pista",
    responsavel: "Departamento de Manutenção",
    contato: "manutencao@email.com",
    data: "2025-06-18",
    horaInicio: 8,
    horaFim: 18,
    status: "confirmado",
    projetoId: null,
    tipo: "interno",
    descricao: "Manutenção preventiva da pista de atletismo.",
    recorrente: false,
  },
  {
    id: "agd-017",
    espacoId: "esp-003",
    titulo: "Demonstração de Ginástica",
    responsavel: "Fernanda Costa",
    contato: "fernanda.costa@email.com",
    data: "2025-06-22",
    horaInicio: 15,
    horaFim: 17,
    status: "conflito",
    projetoId: "proj-003",
    tipo: "interno",
    descricao: "Demonstração de ginástica para visitantes.",
    recorrente: false,
  },
  {
    id: "agd-018",
    espacoId: "esp-002",
    titulo: "Aula de Hidroginástica para Terceira Idade",
    responsavel: "Programa Melhor Idade",
    contato: "melhoridade@email.com",
    data: "2025-06-16",
    horaInicio: 10,
    horaFim: 11,
    status: "confirmado",
    projetoId: null,
    tipo: "externo",
    descricao: "Aula de hidroginástica para grupo da terceira idade.",
    recorrente: true,
    padraoRecorrencia: "semanal",
    diasRecorrencia: "Segunda, Quarta, Sexta",
    dataFimRecorrencia: "2025-12-19",
  },
  {
    id: "agd-019",
    espacoId: "esp-007",
    titulo: "Palestra Motivacional",
    responsavel: "Departamento de Psicologia",
    contato: "psicologia@email.com",
    data: "2025-06-17",
    horaInicio: 16,
    horaFim: 18,
    status: "confirmado",
    projetoId: null,
    tipo: "interno",
    descricao: "Palestra motivacional com atleta olímpico convidado.",
    recorrente: false,
  },
  {
    id: "agd-020",
    espacoId: "esp-008",
    titulo: "Curso de Primeiros Socorros",
    responsavel: "Departamento Médico",
    contato: "medico@email.com",
    data: "2025-06-19",
    horaInicio: 9,
    horaFim: 12,
    status: "confirmado",
    projetoId: null,
    tipo: "interno",
    descricao: "Curso de primeiros socorros para técnicos e funcionários.",
    recorrente: false,
  },
]
