// Dados simulados para espaços
export const espacosMock = [
  {
    id: "esp-001",
    nome: "Quadra Poliesportiva Principal",
    tipo: "quadra",
    capacidade: 200,
    localizacao: "Bloco A, Piso Térreo",
    horarioFuncionamento: "08:00 às 22:00",
    descricao:
      "Quadra poliesportiva coberta com dimensões oficiais, adequada para competições de basquete, vôlei, futsal e handebol. Possui arquibancada com capacidade para 200 espectadores, sistema de som e placar eletrônico.",
    recursos: [
      "Piso emborrachado de alta performance",
      "Tabelas de basquete retráteis",
      "Redes de vôlei e futsal",
      "Placar eletrônico",
      "Sistema de som",
      "Vestiários masculino e feminino",
    ],
    imagens: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    status: "disponivel",
    agendamentos: 12,
    manutencoes: [
      {
        tipo: "Manutenção Preventiva",
        data: "15/07/2025",
        descricao: "Revisão do piso e equipamentos",
      },
    ],
    estatisticas: {
      taxaOcupacao: "75%",
      totalAgendamentos: "42",
      horasUtilizadas: "128h",
    },
  },
  {
    id: "esp-002",
    nome: "Piscina Olímpica",
    tipo: "piscina",
    capacidade: 150,
    localizacao: "Bloco B, Área Externa",
    horarioFuncionamento: "06:00 às 21:00",
    descricao:
      "Piscina olímpica com 50 metros de comprimento, 25 metros de largura e 8 raias. Profundidade variando de 1,40m a 2,20m. Temperatura controlada entre 25°C e 28°C. Ideal para treinamentos e competições de natação.",
    recursos: [
      "8 raias com separadores anti-ondas",
      "Blocos de partida oficiais",
      "Sistema de cronometragem eletrônica",
      "Arquibancada para 150 espectadores",
      "Sistema de filtragem e tratamento de água",
      "Vestiários com armários e chuveiros",
    ],
    imagens: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    status: "manutencao",
    agendamentos: 0,
    manutencoes: [
      {
        tipo: "Limpeza e Tratamento",
        data: "10/06/2025 - 15/06/2025",
        descricao: "Esvaziamento completo, limpeza e tratamento da água",
      },
    ],
    estatisticas: {
      taxaOcupacao: "82%",
      totalAgendamentos: "38",
      horasUtilizadas: "145h",
    },
  },
  {
    id: "esp-003",
    nome: "Ginásio de Ginástica Artística",
    tipo: "ginasio",
    capacidade: 120,
    localizacao: "Bloco C, Piso 1",
    horarioFuncionamento: "08:00 às 20:00",
    descricao:
      "Ginásio especializado em ginástica artística e rítmica, equipado com todos os aparelhos oficiais. Piso com amortecimento especial e área de segurança com colchões. Ideal para treinamentos e competições de ginástica.",
    recursos: [
      "Aparelhos oficiais de ginástica artística",
      "Área de solo com 12x12m",
      "Fosso de espuma para treinamento de saltos",
      "Espelhos em toda a extensão de uma parede",
      "Sistema de som",
      "Vestiários",
    ],
    imagens: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    status: "disponivel",
    agendamentos: 8,
    manutencoes: [],
    estatisticas: {
      taxaOcupacao: "65%",
      totalAgendamentos: "28",
      horasUtilizadas: "98h",
    },
  },
  {
    id: "esp-004",
    nome: "Pista de Atletismo",
    tipo: "pista",
    capacidade: 300,
    localizacao: "Área Externa",
    horarioFuncionamento: "06:00 às 19:00",
    descricao:
      "Pista de atletismo oficial com 400 metros e 8 raias. Superfície sintética de alta performance. Inclui áreas para salto em distância, salto em altura, arremesso de peso e lançamento de dardo.",
    recursos: [
      "Pista com 8 raias",
      "Áreas para todas as modalidades de campo",
      "Sistema de cronometragem eletrônica",
      "Arquibancada para 300 espectadores",
      "Iluminação para treinos noturnos",
    ],
    imagens: ["/placeholder.svg?height=600&width=800", "/placeholder.svg?height=600&width=800"],
    status: "disponivel",
    agendamentos: 15,
    manutencoes: [],
    estatisticas: {
      taxaOcupacao: "70%",
      totalAgendamentos: "35",
      horasUtilizadas: "112h",
    },
  },
  {
    id: "esp-005",
    nome: "Sala de Musculação",
    tipo: "sala",
    capacidade: 50,
    localizacao: "Bloco D, Piso 2",
    horarioFuncionamento: "06:00 às 22:00",
    descricao:
      "Sala de musculação completa com equipamentos modernos para treinamento de força e condicionamento físico. Área de 300m² com zonas específicas para diferentes grupos musculares.",
    recursos: [
      "Equipamentos de musculação de última geração",
      "Área de peso livre",
      "Área cardiovascular com esteiras e bicicletas",
      "Espelhos",
      "Sistema de som",
      "Ar-condicionado",
    ],
    imagens: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    status: "ocupado",
    agendamentos: 20,
    manutencoes: [],
    estatisticas: {
      taxaOcupacao: "90%",
      totalAgendamentos: "56",
      horasUtilizadas: "168h",
    },
  },
  {
    id: "esp-006",
    nome: "Quadra de Tênis",
    tipo: "quadra",
    capacidade: 50,
    localizacao: "Área Externa",
    horarioFuncionamento: "07:00 às 20:00",
    descricao:
      "Quadra de tênis oficial com superfície de saibro. Dimensões padrão para competições nacionais e internacionais. Cercada com alambrado e iluminação para jogos noturnos.",
    recursos: [
      "Superfície de saibro de alta qualidade",
      "Rede oficial",
      "Cadeira de árbitro",
      "Pequena arquibancada para 50 espectadores",
      "Iluminação para jogos noturnos",
    ],
    imagens: ["/placeholder.svg?height=600&width=800", "/placeholder.svg?height=600&width=800"],
    status: "disponivel",
    agendamentos: 10,
    manutencoes: [
      {
        tipo: "Manutenção da Superfície",
        data: "20/06/2025",
        descricao: "Nivelamento e reposição de saibro",
      },
    ],
    estatisticas: {
      taxaOcupacao: "60%",
      totalAgendamentos: "25",
      horasUtilizadas: "85h",
    },
  },
]
