// Dados simulados para projetos
export const projetosMock = [
  {
    id: "proj-001",
    nome: "Natação Olímpica",
    modalidade: "Natação",
    descricao: "Projeto de treinamento de alto rendimento para atletas de natação com potencial olímpico.",
    dataInicio: "01/01/2025",
    dataFim: "31/12/2025",
    responsavel: "Carlos Mendes",
    espacos: ["esp-002"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Atletas de 14 a 21 anos com experiência em competições",
    metasConcluidas: 2,
    metasTotal: 6,
    proximaAcao: "Avaliação de desempenho (15/06/2025)",
  },
  {
    id: "proj-002",
    nome: "Basquete Juvenil",
    modalidade: "Basquete",
    descricao: "Formação de jovens atletas de basquete entre 14 e 17 anos.",
    dataInicio: "15/02/2025",
    dataFim: "15/12/2025",
    responsavel: "Ana Paula Silva",
    espacos: ["esp-001"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Adolescentes de 14 a 17 anos",
    metasConcluidas: 1,
    metasTotal: 5,
  },
  {
    id: "proj-003",
    nome: "Ginástica Artística Feminina",
    modalidade: "Ginástica Artística",
    descricao: "Treinamento de ginastas femininas para competições nacionais e internacionais.",
    dataInicio: "01/03/2025",
    dataFim: "30/11/2025",
    responsavel: "Fernanda Costa",
    espacos: ["esp-003"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Meninas de 8 a 16 anos",
    metasConcluidas: 2,
    metasTotal: 7,
  },
  {
    id: "proj-004",
    nome: "Atletismo - Velocistas",
    modalidade: "Atletismo - Corridas",
    descricao: "Desenvolvimento de atletas para provas de velocidade (100m, 200m e 400m).",
    dataInicio: "01/02/2025",
    dataFim: "30/10/2025",
    responsavel: "Roberto Almeida",
    espacos: ["esp-004"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Jovens de 15 a 20 anos",
    metasConcluidas: 1,
    metasTotal: 4,
  },
  {
    id: "proj-005",
    nome: "Tênis de Alto Rendimento",
    modalidade: "Tênis",
    descricao: "Treinamento intensivo para tenistas com potencial para circuito profissional.",
    dataInicio: "15/01/2025",
    dataFim: "15/12/2025",
    responsavel: "Marcelo Santos",
    espacos: ["esp-006"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Tenistas de 14 a 21 anos",
    metasConcluidas: 2,
    metasTotal: 6,
  },
  {
    id: "proj-006",
    nome: "Preparação Física Multiesportiva",
    modalidade: "Multiesportiva",
    descricao: "Programa de condicionamento físico para atletas de diversas modalidades.",
    dataInicio: "01/01/2025",
    dataFim: "31/12/2025",
    responsavel: "Juliana Martins",
    espacos: ["esp-005", "esp-004"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Atletas de 15 a 30 anos",
    metasConcluidas: 3,
    metasTotal: 8,
  },
  {
    id: "proj-007",
    nome: "Futsal Feminino",
    modalidade: "Futsal",
    descricao: "Treinamento e competições para a equipe feminina de futsal.",
    dataInicio: "01/03/2025",
    dataFim: "30/11/2025",
    responsavel: "Pedro Oliveira",
    espacos: ["esp-001"],
    status: "em_andamento",
    tipo: "Esportivo",
    publicoAlvo: "Mulheres de 16 a 25 anos",
    metasConcluidas: 1,
    metasTotal: 5,
  },
  {
    id: "proj-008",
    nome: "Esporte na Comunidade",
    modalidade: "Multiesportiva",
    descricao: "Projeto social para levar atividades esportivas a comunidades carentes.",
    dataInicio: "01/04/2025",
    dataFim: "01/04/2026",
    responsavel: "Mariana Souza",
    espacos: ["esp-001", "esp-004"],
    status: "planejado",
    tipo: "Social",
    publicoAlvo: "Crianças e adolescentes de comunidades carentes",
    metasConcluidas: 0,
    metasTotal: 6,
  },
  {
    id: "proj-009",
    nome: "Olimpíadas Escolares",
    modalidade: "Multiesportiva",
    descricao: "Competição entre escolas públicas e privadas em diversas modalidades.",
    dataInicio: "01/08/2025",
    dataFim: "30/09/2025",
    responsavel: "Ricardo Gomes",
    espacos: ["esp-001", "esp-002", "esp-003", "esp-004"],
    status: "planejado",
    tipo: "Educacional",
    publicoAlvo: "Estudantes de 10 a 17 anos",
    metasConcluidas: 0,
    metasTotal: 4,
  },
  {
    id: "proj-010",
    nome: "Natação para Todos",
    modalidade: "Natação",
    descricao: "Projeto de inclusão social através da natação para pessoas com deficiência.",
    dataInicio: "01/03/2025",
    dataFim: "01/03/2026",
    responsavel: "Luciana Ferreira",
    espacos: ["esp-002"],
    status: "planejado",
    tipo: "Social",
    publicoAlvo: "Pessoas com deficiência de todas as idades",
    metasConcluidas: 0,
    metasTotal: 5,
  },
  {
    id: "proj-011",
    nome: "Festival Cultural Esportivo",
    modalidade: "Multiesportiva",
    descricao: "Evento que combina apresentações culturais e competições esportivas.",
    dataInicio: "15/07/2025",
    dataFim: "30/07/2025",
    responsavel: "Carla Rodrigues",
    espacos: ["esp-001", "esp-003"],
    status: "planejado",
    tipo: "Cultural",
    publicoAlvo: "Público geral",
    metasConcluidas: 0,
    metasTotal: 3,
  },
  {
    id: "proj-012",
    nome: "Judô na Escola",
    modalidade: "Judô",
    descricao: "Projeto educacional que leva o judô para escolas públicas.",
    dataInicio: "01/02/2025",
    dataFim: "30/11/2025",
    responsavel: "Paulo Tanaka",
    espacos: [],
    status: "planejado",
    tipo: "Educacional",
    publicoAlvo: "Estudantes de 8 a 14 anos",
    metasConcluidas: 0,
    metasTotal: 4,
  },
]
